import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.IVAN_SUPABASE_CONFIG||{}, supabase=cfg.supabaseUrl&&cfg.supabaseAnonKey?createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=id=>document.getElementById(id), sections={posts:'Publicaciones del blog',homeSlides:'Diapositivas de portada',homeCards:'Contenido destacado',gallery:'Galería de imágenes'};
let content={posts:[],homeSlides:[],homeCards:[],gallery:[]},active='posts',editing='';
const clean=value=>String(value??'').trim(), escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const message=(text,error=false)=>{$('admin-message').textContent=text;$('admin-message').className=error?'error':'success'}, loginMessage=(text,error=false)=>{$('login-message').textContent=text;$('login-message').className=error?'error':''};
function showAdmin(email){$('login-screen').hidden=true;$('admin-screen').hidden=false;$('logout').hidden=false;$('user-email').textContent=email||'';render()}
function render(){const list=content[active]||[];$('section-title').textContent=sections[active];$('item-count').textContent=`${list.length} elementos`;$('item-list').innerHTML=list.length?list.map(item=>`<article class="admin-row"><div class="admin-row-copy"><strong>${escape(item.title||'Sin título')}</strong><small>${escape(item.description||item.image||'Sin descripción')} · ${item.published===false?'Borrador':'Publicado'}</small></div><div class="admin-row-actions"><button type="button" data-up="${escape(item.id)}">↑</button><button type="button" data-down="${escape(item.id)}">↓</button><button type="button" data-edit="${escape(item.id)}">Editar</button></div></article>`).join(''):'<p>No hay contenido en esta sección.</p>';bindRows()}
function bindRows(){$('item-list').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$('item-list').querySelectorAll('[data-up],[data-down]').forEach(b=>b.onclick=()=>move(b.dataset.up||b.dataset.down,Boolean(b.dataset.up)))}
function move(id,up){const list=content[active],i=list.findIndex(x=>x.id===id),n=i+(up?-1:1);if(i<0||n<0||n>=list.length)return;[list[i],list[n]]=[list[n],list[i]];render();message('Orden actualizado. Guarda los cambios para publicarlo.')}
function openEditor(id=''){editing=id;const item=content[active].find(x=>x.id===id)||{};$('editor-title').textContent=id?'Editar contenido':'Añadir contenido';$('field-id').value=id;$('field-title').value=item.title||'';$('field-description').value=item.description||'';$('field-image').value=item.image||'';$('field-images').value=(item.images||[]).join('\n');$('field-link').value=item.link||'';$('field-date').value=/^\d{4}-\d{2}-\d{2}$/.test(item.date||'')?item.date:'';$('field-category').value=item.category||'';$('field-type').value=item.type||'standard';$('field-published').checked=item.published!==false;$('field-type').parentElement.hidden=active!=='posts';$('field-date').parentElement.hidden=active!=='posts';$('field-category').parentElement.hidden=active!=='posts';$('images-wrap').hidden=active!=='posts';$('field-link').parentElement.hidden=active==='gallery'||active==='posts';$('editor').hidden=false;$('editor').scrollIntoView({behavior:'smooth'});$('field-title').focus()}
function closeEditor(){$('editor').hidden=true;editing=''}
function saveEditor(event){event.preventDefault();const existing=content[active].find(x=>x.id===editing),item={...(existing||{}),id:editing||`${active}-${Date.now()}`,title:clean($('field-title').value),description:clean($('field-description').value),image:clean($('field-image').value),published:$('field-published').checked};if(active==='posts'){item.type=$('field-type').value;item.date=$('field-date').value;item.category=clean($('field-category').value);item.images=$('field-images').value.split('\n').map(clean).filter(Boolean)}else if(active!=='gallery')item.link=clean($('field-link').value)||'blog.html';if(!item.title)return message('Escribe un título.',true);if(existing)Object.assign(existing,item);else content[active].unshift(item);closeEditor();render();message('Contenido aplicado. Pulsa “Guardar cambios” para publicarlo.')}
async function loadContent(){const {data,error}=await supabase.from('site_content').select('content').eq('id',true).maybeSingle();if(error)throw error;const remote=data?.content;if(remote?.posts?.length||remote?.homeSlides?.length||remote?.homeCards?.length||remote?.gallery?.length){content=remote;return}const response=await fetch('content/site.json',{cache:'no-store'});if(response.ok)content=await response.json()}
async function init(){if(!supabase)return loginMessage('Falta la configuración de Supabase.',true);const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:admin,error}=await supabase.from('admin_users').select('email').eq('user_id',session.user.id).maybeSingle();if(error||!admin){await supabase.auth.signOut();return loginMessage('Esta cuenta no tiene permisos de administración.',true)}await loadContent();showAdmin(session.user.email)}
$('login-form').onsubmit=async e=>{e.preventDefault();if(!supabase)return loginMessage('La conexión con Supabase no está disponible.',true);loginMessage('Comprobando…');try{const {error}=await supabase.auth.signInWithPassword({email:clean($('login-email').value).toLowerCase(),password:$('login-password').value});if(error)throw error;await loadContent();showAdmin($('login-email').value)}catch{loginMessage('No se pudo iniciar sesión. Revisa el correo y la contraseña.',true)}};
$('logout').onclick=async()=>{await supabase?.auth.signOut();location.reload()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));closeEditor();render()});$('add-item').onclick=()=>openEditor();$('close-editor').onclick=closeEditor;$('content-form').onsubmit=saveEditor;$('delete-item').onclick=()=>{if(!editing)return;content[active]=content[active].filter(x=>x.id!==editing);closeEditor();render();message('Elemento eliminado. Guarda los cambios para publicarlo.')};
$('save-all').onclick=async()=>{try{const {error}=await supabase.from('site_content').upsert({id:true,content,updated_at:new Date().toISOString()});if(error)throw error;message('Cambios guardados y publicados.')}catch(error){message(`No se pudo guardar: ${error.message}`,true)}};
function theme(value){document.documentElement.dataset.theme=value;localStorage.setItem('ivan-admin-theme',value);$('theme-toggle').textContent=value==='dark'?'Claro':'Oscuro'}theme(localStorage.getItem('ivan-admin-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));$('theme-toggle').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');init().catch(error=>loginMessage(`No se pudo abrir el panel: ${error.message}`,true));
