(function(){
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const visible=list=>(list||[]).filter(item=>item.published!==false);
  const months={Jan:'01',Feb:'02',Mar:'03',Apr:'04',May:'05',Jun:'06',Jul:'07',Aug:'08',Sep:'09',Oct:'10',Nov:'11',Dec:'12'};
  const parts=value=>{const raw=String(value||'');if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const [year,month,day]=raw.split('-');return{year,month,day}}const [year,name,day]=raw.split('-');return{year,month:months[name]||'01',day:day||'01'}};
  const monthName=number=>['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Math.max(0,Number(number)-1)];
  const icon=type=>type==='image'?'feather-icon-image':type==='gallery'?'feather-icon-layers':'feather-icon-paper';
  function media(post){const images=post.type==='gallery'&&post.images?.length?post.images:[post.image].filter(Boolean);if(!images.length)return'';if(post.type==='gallery')return`<div class="gridblock-owlcarousel-wrap clearfix"><div class="owl-carousel owl-slideshow-element">${images.map(image=>`<div class="gridblock-slideshow-element"><a data-lightbox="magnific-image-gallery" class="slideshow-lightbox" href="${escape(image)}"><img src="${escape(image)}" alt="${escape(post.title)}" loading="lazy"></a></div>`).join('')}</div></div>`;return`<div class="post-format-media"><a title="${escape(post.title)}" class="postformat-image-lightbox" data-lightbox="magnific-image" href="${escape(images[0])}"><span class="lightbox-indicate"><i class="feather-icon-maximize"></i></span><img src="${escape(images[0])}" alt="${escape(post.title)}" class="postformat-image" loading="lazy"></a></div>`}
  function post(post){const date=parts(post.date);return`<div class="entry-content-wrapper"><div class="topseperator entry-wrapper post-${escape(post.type||'standard')}-wrapper clearfix"><div class="blog-details-section"><div class="blog-details-section-inner"><span class="the-day">${escape(date.day)}</span><span class="the-month">${monthName(date.month)}</span><span class="the-year">${escape(date.year)}</span></div></div><div class="blog-content-section"><div class="post type-post status-publish format-${escape(post.type||'standard')}">${media(post)}<div class="entry-content postformat_contents clearfix"><div class="entry-post-title"><h2><a rel="bookmark">${escape(post.title)}</a></h2></div><p>${escape(post.description)}</p></div><div class="postsummarywrap"><div class="datecomment clearfix"><i class="${icon(post.type)}"></i><span class="post-meta-category"><a rel="category tag">${escape(post.category||'Blog')}</a></span></div></div></div></div></div></div>`}
  function renderBlog(data){const wrap=document.querySelector('.contents-wrap');if(wrap)wrap.innerHTML=visible(data.posts).map(post).join('')}
  function renderCards(data){const wrap=document.querySelector('#owl-6033-691b40131541b');if(!wrap)return;wrap.innerHTML=visible(data.homeCards).map(item=>`<div class="slideshow-box-wrapper"><div class="slideshow-box-image"><a href="${escape(item.link||'blog.html')}"><img src="${escape(item.image)}" alt="${escape(item.title)}" class="displayed-image"></a></div><div class="slideshow-box-content"><div class="slideshow-box-content-inner"><div class="slideshow-box-title"><a href="${escape(item.link||'blog.html')}">${escape(item.title)}</a></div><div class="slideshow-box-description">${escape(item.description)}</div></div></div></div>`).join('')}
  function renderGallery(data){const images=visible(data.gallery),marker=document.getElementById('foto-dinamica');if(!marker||!images.length)return;window.IVAN_GALLERY=images.map(item=>item.image);document.documentElement.style.setProperty('--mi-foto',`url("${images[0].image.replace(/["']/g,'')}")`)}
  function apply(data){window.IVAN_SITE_CONTENT=data;renderBlog(data);renderCards(data);renderGallery(data);document.dispatchEvent(new CustomEvent('ivan-content-ready',{detail:data}))}
  function remote(){const c=window.IVAN_SUPABASE_CONFIG||{};if(!c.supabaseUrl||!c.supabaseAnonKey)return Promise.reject();return fetch(`${c.supabaseUrl}/rest/v1/site_content?select=content&id=eq.true`,{headers:{apikey:c.supabaseAnonKey,Authorization:`Bearer ${c.supabaseAnonKey}`}}).then(r=>r.ok?r.json():Promise.reject()).then(rows=>{const data=rows[0]?.content;if(!data?.posts?.length&&!data?.homeSlides?.length&&!data?.homeCards?.length&&!data?.gallery?.length)return Promise.reject();return data})}
  function load(){const local=(location.pathname.includes('/images/')?'../':'')+'content/site.json';return remote().catch(()=>window.IVAN_SITE_DATA||fetch(local,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()))}
  load().then(apply).then(()=>{if(window.jQuery?.supersized){const original=window.jQuery.supersized;const wrapped=function(options){const slides=visible(window.IVAN_SITE_CONTENT.homeSlides);if(slides.length)options.slides=slides.map(item=>({image:item.image,alttext:item.title||'',title:`<div class="fullscreen-slideshow-color" data-color="bright"></div><div class="slideshow-content-wrap"><div class="slideshow_title slideshow_title_animation">${escape(item.title)}</div><div class="slideshow_caption"><p>${escape(item.description)}</p><br /></div><div class="slideshow_content_link"><a class="supersized-button" href="${escape(item.link||'blog.html')}">Blog</a></div></div>`,thumb:'',url:''}));return original.call(this,options)};Object.assign(wrapped,original);window.jQuery.supersized=wrapped}}).catch(()=>{});
}());
